package com.example.linkedin.model;

import jakarta.validation.constraints.NotBlank;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a response generated by the LLM agent.
 */
public class GeneratedResponse {
    @NotBlank
    private String text;
    
    private double confidenceScore;
    
    private String reasoning;
    
    private List<String> warnings;

    // Constructors
    public GeneratedResponse() {
        this.warnings = new ArrayList<>();
    }

    public GeneratedResponse(String text, double confidenceScore, String reasoning) {
        this.text = text;
        this.confidenceScore = confidenceScore;
        this.reasoning = reasoning;
        this.warnings = new ArrayList<>();
    }

    // Getters and Setters
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public double getConfidenceScore() {
        return confidenceScore;
    }

    public void setConfidenceScore(double confidenceScore) {
        this.confidenceScore = confidenceScore;
    }

    public String getReasoning() {
        return reasoning;
    }

    public void setReasoning(String reasoning) {
        this.reasoning = reasoning;
    }

    public List<String> getWarnings() {
        return warnings;
    }

    public void setWarnings(List<String> warnings) {
        this.warnings = warnings;
    }

    public void addWarning(String warning) {
        this.warnings.add(warning);
    }
}
